### ISSUE TITLE
Initial Feature Checklist

### ISSUE THREAD

**Issue by chappjc** [chappjc/webfiles#1]
Basic
- [x] accept and store uploaded files
  - each upload provides a unique ID
- [x] download an uploaded file
  - request by unique ID created during upload
  - download with original file name

Extras
- [x] restrict download to user that uploaded it -- use cookie store (session ID or other value)
- [x] restrict download by token - JWT
- [x] endpoint for listing all files (IDs, names, sizes)
- [x] web UI
- [x] automate deploy (webhook?)
